STEP_SIZE = 0.5
NUM_STEPS = 5
NUM_DECIMALS = 5

# ODE initial values
ODE_Y_0 = 3

# Heart rate
HEART_RATE_RECOVERY = 0.12
HEART_RATE_REST = 60
HEART_RATE_TIME_ZERO = 170

# Heat dissipation
HEAT_DISSIPATION_AMBIENT = 63
HEAT_DISSIPATION_RATE = 0.11
HEAT_DISSIPATION_TIME_ZERO = 158

# Growth/Decay
GROWTH_AND_DECAY_RATE = 0
GROWTH_AND_DECAY_INIT_POP = 10000
